// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaygfhoorpjqjeotdxmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdheWdmaG9vcnBqcWplb3RkeG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2ODcwNjAsImV4cCI6MjA1MjI2MzA2MH0.SEsKhWvM7zpq3Diz_sr-fIgNPtyTsEdhtBFuOP4FAnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);